config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :categories
  devise_for :users
  resources :products
  
  resource :cart, only: [:show] do
  get "add", path: "add/:id"
  get :checkout
  get :clearCart
  end
  
  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  has_one :order_item
  belongs_to :order
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart

  # GET /stocks
  # GET /stocks.json
  
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:availability, :recommended_level, :standard_order, :supplier_name, :supplier_email, :product_id, :order_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.haml
= form_for @stock do |f|
  - if @stock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stock.errors.count, "error")} prohibited this stock from being saved:"
      %ul
        - @stock.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :availability
    = f.number_field :availability
  .field
    = f.label :recommended_level
    = f.number_field :recommended_level
  .field
    = f.label :standard_order
    = f.number_field :standard_order
  .field
    = f.label :supplier_name
    = f.text_field :supplier_name
  .field
    = f.label :supplier_email
    = f.text_field :supplier_email
  
  .actions
    = f.submit 'Save'

app/views/stocks/edit.html.haml
%h1 Editing stock

= render 'form'

= link_to 'Show', @stock
\|
= link_to 'Back', stocks_path

app/views/stocks/index.html.haml
%h1 Listing stocks

%table.table.table-hover
  %thead
    %tr
      %th Availability
      %th Recommended level
      %th Standard order
      %th Supplier name
      %th Supplier email
      %th Product Id


  %tbody
    - @stocks.each do |stock|
      %tr
        %td= stock.availability
        %td= stock.recommended_level
        %td= stock.standard_order
        %td= stock.supplier_name
        %td= stock.supplier_email
        %td= stock.product_id
        %td
          = link_to 'Show', stock
          = link_to 'Edit', edit_stock_path(stock)
          = link_to 'Destroy', stock, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stock', new_stock_path, class: "btn btn-primary"
|
= link_to 'Back to Products', products_path, class: "btn btn-primary"

app/views/stocks/new.html.haml
%h1 New stock

= render 'form'

= link_to 'Back', stocks_path

app/views/stocks/show.html.haml
%p#notice= notice

%p
  %b Availability:
  = @stock.availability
%p
  %b Recommended level:
  = @stock.recommended_level
%p
  %b Standard order:
  = @stock.standard_order
%p
  %b Supplier name:
  = @stock.supplier_name
%p
  %b Supplier email:
  = @stock.supplier_email
%p
  %b Product Id:
  = @stock.product_id


= link_to 'Edit', edit_stock_path(@stock), class: "btn btn-primary"
\|
= link_to 'Back to Products', products_path, class: "btn btn-primary"