config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :categories
  devise_for :users
  resources :products
  
  resource :cart, only: [:show] do
  get "add", path: "add/:id"
  get :checkout
  get :clearCart
  end
  
  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_reader :items
  
  #so the session data persists all of the data in the cart
  #circling each item from the cart's item hash and creating a new mapping for that
  def self.build_from_hash hash
  #check if there is a cart item inside the hash, this hash represents the session
    items = if hash["cart"] then 
	  hash["cart"]["items"].map do |item_data|
	  CartItem.new item_data["product_id"], item_data["quantity"]
	  end
	else
	  []
	end
	
	new items
  end
  #initializing the cart, items defaults to an empty array
  def initialize items = []
    @items = items
  end
  #adding individual products to the cart
  def add_item product_id
  #retrieve items there with this product id
    item = @items.find { |item| item.product_id == product_id }
  # is there is already an item there increment otherwise add a new item
	if item
	#if there is an item with this product id then we will increment this items quantity,
	#calling the increment method from cart_item.rb. If not we will just add the item to the cart.
	  item.increment
	else
	  @items << CartItem.new(product_id)
	end
  end
  #since items is an array, we can use the empty method
  def empty?
    @items.empty?
  end
  #number of items in the cart
  def count
    @items.inject(0) { |sum, item| sum + item.quantity }
  end
  # to build a list of items in an array
  #serialize contents of entire cart into a hash
  def serialize
  #serialize contents of entire cart into a hash
  #item picks up on the items instance variable
  #take an item which will be used to create a brand new hash which will contain
  #two strings product_id and quantity
    items = @items.map do |item|
	  {
	    "product_id" => item.product_id,
		"quantity" => item.quantity
	  }
	end
	#hash being returned from building block above 
    {
	  "items" =>  items
	}
  end
  #calculating the total price of items
  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart
  
  def add
    @cart.add_item params[:id]
	session["cart"] = @cart.serialize
	product = Product.find params[:id]
	redirect_to :back, notice: "Added #{product.name} to cart"
  end
  
  def clearCart
    # set the session variable to nil and redirect
	session[:cart] = nil
	redirect_to root_path
  end
  
  def show
  end
  
  def checkout
    @order_form = OrderForm.new user: User.new

  end
end

app/views/carts/checkout.html.erb
<h2>Checkout</h2>
<h4>You are checking out the following products:</h4>
<ul>
  <% @cart.items.each do |item| %>
    <li>
      <em>
        Items Ordered: <%= item.quantity %>&nbsp
      </em>
      <em>
        Stocks Available: <%= item.stock.availability %>&nbsp
      </em>	  
      <%= item.product.name %>
      <%= number_to_currency item.total_price, :unit => "Price: € " %>
    </li>
  <% end %>
</ul>
<p>
  <strong>
    Total price:
    <%= number_to_currency(@cart.total_price, :unit => "€ ") %>
  </strong>
</p>
  <!-- using form builder to create orders form -->
<%= form_for @order_form, url: orders_path do |f| %>
  <%= render "orders/errors" %>
  
  <h4>Some of your personal details</h4>
  <%= f.fields_for :user, f.object.user do |u| %>
    <div class="form-group">
      <p>
        <%= u.text_field :name, placeholder: "Name", class: "form-control input-lg" %>
      </p>
      <p>
        <%= u.text_field :email, placeholder: "Email", class: "form-control" %>
        <span class="help-block">This will help you track your order more effectively.</span>
      </p>
    </div>
    <div class="form-group">
      <div class="row">
        <p class="col-md-6">
          <%= u.text_field :address, placeholder: "Address", class: "form-control" %>
        </p>
        <p class="col-md-3">
          <%= u.text_field :postal_code, placeholder: "Postal code", class: "form-control" %>
        </p>
        <p class="col-md-3">
          <%= u.text_field :city, placeholder: "City", class: "form-control" %>
        </p>
      </div>
      <p>
        <%= u.country_select :country, {priority_countries: [ "IE", "GB", "US" ] }, { class:"form-control"} %>
      </p>
      <p>
        <%= u.text_field :phone, placeholder: "Phone", class: "form-control" %>
      </p>
    </div>
  <% end %>  
    <p>
      <%= f.submit "Place order", class: "btn btn-primary" %>
	  |
	  <%= link_to "Back to Cart", cart_path, class: "btn btn-primary" %>
      |
	  <%= link_to 'Continue Shopping', products_path, class: "btn btn-primary" %>
	</p>
<% end %>

app/views/carts/show.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Product</th>
      <th>Price</th>
    </tr>
  </thead>
  <% @cart.items.each do |item| %>
    <tr>
      <td>
       Items Ordered: <%= item.quantity %>
       </br>
        Stocks Available: <%= item.stock.availability %>
      </td>	
      <td>
        <%= image_tag item.product.image.thumb %>
        <%= link_to item.product.name, item.product %>
      </td>
      <td class="text-right">
        <%= (number_to_currency(item.total_price, options= {:unit => "€"}) ) %>
      </td>
    </tr>	  
  <% end %>
</table>
<p><b>
  Total Price:
  <%= (number_to_currency(@cart.total_price, options= {:unit => "€"})) %>
</b></p>
<p>
  <%= link_to 'Continue Shopping', products_path, class: "btn btn-primary" %>
  |
  <%=link_to "clearCart", clearCart_cart_path, class: "btn btn-primary" %>
  |
  <%= link_to "Checkout", checkout_cart_path, class: "btn btn-primary" %>
</p>