config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :categories
  devise_for :users
  resources :products
  
  resource :cart, only: [:show] do
  get "add", path: "add/:id"
  get :checkout
  get :clearCart
  end
  
  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
  validates_presence_of :name, :price
  validates_numericality_of :price
  
  belongs_to :category
  has_one :stock
  has_one :order_item

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_stock, only: [:show, :update, :destroy]
  before_filter :initialize_cart


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
	@stock = Stock.find(params[:id])
  end


  # GET /products/new
  def new
    @product = Product.new
    
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @stock = Stock.new
    @stock.availability = 0

    @stock.save
    @product.stock = @stock
    respond_to do |format|
      if @product.save
        format.html { redirect_to edit_stock_path(@stock.id), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        #adding redirect to stock updates for convenience
		
		@stock = @product.stock
        format.html { redirect_to edit_stock_path(@stock.id), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    
    def set_stock
      @stock = @product.stock
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id, :stock_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<!-- adding multipart so form takes files to server -->
<%= form_for @product, multipart: true do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:" %>
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.map { |c| [c.name, c.id ] } %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/products/_products_table.html.erb

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>
  <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to product.name, product %>
      </td>
      <td>
        <%= number_to_currency product.price %>
      </td>
      <td>
        <%= image_tag product.image.thumb %>
      </td>
  
      <td>
      <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_product_path(product) %>
          <%= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
     <% end %>
</table>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<%= render 'form' %>
<%= link_to 'Show', @product %>
|
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<%= render "products/products_table" %>

<br/>
<% if current_user && current_user.admin? %>
  <p>
    <%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>
  <%= @product.name %>
</h1>
<p>
  <%= @product.description %>
</p>
<p>
  <%= number_to_currency @product.price, :unit => "Price: € " %>
</p>
<p>
  <%= image_tag @product.image, height: "300" %>
</p>
<p>
  Category: <%= @product.category.name %>  ,Stocks Available: <%= @stock.availability %>
</p>
<p>
  <% if @stock.availability != 0 && @stock.availability != nil  %>
    <%= link_to "Add to cart", add_cart_path, class: "btn btn-primary" %>
	|
	<%= link_to "Go to Cart", cart_path, class: "btn btn-primary" %>
  <% else %>
    <p>Sorry Out of stock</p>
  <% end %>
</p>
<p>
<% if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary"  %>
  |
<% end %> 
  <%= link_to 'Back', products_path, class: "btn btn-primary" %>
</p>